CREATE TABLE HEALTH_CARE_ENROLLEE_DEPENDENTS (
   ID int NOT NULL AUTO_INCREMENT,
   ENROLLE_ID int NOT NULL,
   DEPENDENT_NAME varchar(30) NOT NULL,
   BIRTH_DATE date DEFAULT NULL,
   PRIMARY KEY (ID)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
 
 
 CREATE TABLE HEALTH_CARE_ENROLLEE_DETAILS (
   ENROLLEE_ID int NOT NULL AUTO_INCREMENT,
   ENROLLEE_NAME varchar(30) NOT NULL,
   ACTIVATION_STATUS tinyint DEFAULT '1',
   BIRTH_DATE date DEFAULT NULL,
   PHONE_NUMBER varchar(11) NOT NULL,
   ENROLL_DATE date DEFAULT NULL,
   HAS_DEPENDENCIES tinyint DEFAULT '1',
   PRIMARY KEY (ENROLLEE_ID)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;